// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: msp_apm_exception.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on EXCEPTION_EVENT_ID_LIST_Request with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *EXCEPTION_EVENT_ID_LIST_Request) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EXCEPTION_EVENT_ID_LIST_Request with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// EXCEPTION_EVENT_ID_LIST_RequestMultiError, or nil if none found.
func (m *EXCEPTION_EVENT_ID_LIST_Request) ValidateAll() error {
	return m.validate(true)
}

func (m *EXCEPTION_EVENT_ID_LIST_Request) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return EXCEPTION_EVENT_ID_LIST_RequestMultiError(errors)
	}

	return nil
}

// EXCEPTION_EVENT_ID_LIST_RequestMultiError is an error wrapping multiple
// validation errors returned by EXCEPTION_EVENT_ID_LIST_Request.ValidateAll()
// if the designated constraints aren't met.
type EXCEPTION_EVENT_ID_LIST_RequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EXCEPTION_EVENT_ID_LIST_RequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EXCEPTION_EVENT_ID_LIST_RequestMultiError) AllErrors() []error { return m }

// EXCEPTION_EVENT_ID_LIST_RequestValidationError is the validation error
// returned by EXCEPTION_EVENT_ID_LIST_Request.Validate if the designated
// constraints aren't met.
type EXCEPTION_EVENT_ID_LIST_RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EXCEPTION_EVENT_ID_LIST_RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EXCEPTION_EVENT_ID_LIST_RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EXCEPTION_EVENT_ID_LIST_RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EXCEPTION_EVENT_ID_LIST_RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EXCEPTION_EVENT_ID_LIST_RequestValidationError) ErrorName() string {
	return "EXCEPTION_EVENT_ID_LIST_RequestValidationError"
}

// Error satisfies the builtin error interface
func (e EXCEPTION_EVENT_ID_LIST_RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEXCEPTION_EVENT_ID_LIST_Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EXCEPTION_EVENT_ID_LIST_RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EXCEPTION_EVENT_ID_LIST_RequestValidationError{}

// Validate checks the field values on EXCEPTION_EVENT_Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *EXCEPTION_EVENT_Request) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EXCEPTION_EVENT_Request with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EXCEPTION_EVENT_RequestMultiError, or nil if none found.
func (m *EXCEPTION_EVENT_Request) ValidateAll() error {
	return m.validate(true)
}

func (m *EXCEPTION_EVENT_Request) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return EXCEPTION_EVENT_RequestMultiError(errors)
	}

	return nil
}

// EXCEPTION_EVENT_RequestMultiError is an error wrapping multiple validation
// errors returned by EXCEPTION_EVENT_Request.ValidateAll() if the designated
// constraints aren't met.
type EXCEPTION_EVENT_RequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EXCEPTION_EVENT_RequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EXCEPTION_EVENT_RequestMultiError) AllErrors() []error { return m }

// EXCEPTION_EVENT_RequestValidationError is the validation error returned by
// EXCEPTION_EVENT_Request.Validate if the designated constraints aren't met.
type EXCEPTION_EVENT_RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EXCEPTION_EVENT_RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EXCEPTION_EVENT_RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EXCEPTION_EVENT_RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EXCEPTION_EVENT_RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EXCEPTION_EVENT_RequestValidationError) ErrorName() string {
	return "EXCEPTION_EVENT_RequestValidationError"
}

// Error satisfies the builtin error interface
func (e EXCEPTION_EVENT_RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEXCEPTION_EVENT_Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EXCEPTION_EVENT_RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EXCEPTION_EVENT_RequestValidationError{}

// Validate checks the field values on EXCEPTION_LIST_Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *EXCEPTION_LIST_Request) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EXCEPTION_LIST_Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EXCEPTION_LIST_RequestMultiError, or nil if none found.
func (m *EXCEPTION_LIST_Request) ValidateAll() error {
	return m.validate(true)
}

func (m *EXCEPTION_LIST_Request) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return EXCEPTION_LIST_RequestMultiError(errors)
	}

	return nil
}

// EXCEPTION_LIST_RequestMultiError is an error wrapping multiple validation
// errors returned by EXCEPTION_LIST_Request.ValidateAll() if the designated
// constraints aren't met.
type EXCEPTION_LIST_RequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EXCEPTION_LIST_RequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EXCEPTION_LIST_RequestMultiError) AllErrors() []error { return m }

// EXCEPTION_LIST_RequestValidationError is the validation error returned by
// EXCEPTION_LIST_Request.Validate if the designated constraints aren't met.
type EXCEPTION_LIST_RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EXCEPTION_LIST_RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EXCEPTION_LIST_RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EXCEPTION_LIST_RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EXCEPTION_LIST_RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EXCEPTION_LIST_RequestValidationError) ErrorName() string {
	return "EXCEPTION_LIST_RequestValidationError"
}

// Error satisfies the builtin error interface
func (e EXCEPTION_LIST_RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEXCEPTION_LIST_Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EXCEPTION_LIST_RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EXCEPTION_LIST_RequestValidationError{}
